import {
  createBranchRequestSchema,
  gitBranchListResponseSchema,
  gitDiscoveryResponseSchema,
  gitFileActionRequestSchema,
  gitFileDiffRequestSchema,
  gitFileDiffResponseSchema,
  gitMutationResponseSchema,
  gitOverviewResponseSchema,
  gitProjectFileStatusResponseSchema,
  gitRemoteOpRequestSchema,
  githubPrCheckoutResponseSchema,
  githubPrChecksResponseSchema,
  githubPrCommitsResponseSchema,
  githubPrConversationSchema,
  githubPrCoreSchema,
  githubPrFileDiffRequestSchema,
  githubPrFileDiffResponseSchema,
  githubPrFilesResponseSchema,
  githubPrInitialSchema,
  githubPrOverviewSchema,
  githubPrListRequestSchema,
  githubPrListResponseSchema,
  githubPrMergeRequestSchema,
  githubPrMergeResponseSchema,
  githubStatusResponseSchema,
  switchBranchRequestSchema,
} from "./index.js";
import { z } from "zod";
import { defineOperation } from "../protocol/operation-definition.schema.js";

const projectIdSchema = z.string().startsWith("proj_");
const projectIdParamsSchema = z.object({ projectId: projectIdSchema });
const gitRepoParamsSchema = projectIdParamsSchema.extend({
  repo: z.string().min(1).default("."),
});
const gitCreateBranchParamsSchema = projectIdParamsSchema.merge(
  createBranchRequestSchema,
);
const gitSwitchBranchParamsSchema = projectIdParamsSchema.merge(
  switchBranchRequestSchema,
);
const gitFileActionParamsSchema = projectIdParamsSchema.merge(
  gitFileActionRequestSchema,
);
const gitFileDiffParamsSchema = projectIdParamsSchema.merge(
  gitFileDiffRequestSchema,
);
const gitRemoteOpParamsSchema = projectIdParamsSchema.merge(
  gitRemoteOpRequestSchema,
);
const githubPrListParamsSchema = projectIdParamsSchema.merge(
  githubPrListRequestSchema,
);
const githubPrParamsSchema = gitRepoParamsSchema.extend({
  number: z.number().int().positive(),
});
const githubPrMergeParamsSchema = projectIdParamsSchema
  .merge(githubPrMergeRequestSchema)
  .extend({ number: z.number().int().positive() });
const githubPrFileDiffParamsSchema = projectIdParamsSchema
  .merge(githubPrFileDiffRequestSchema)
  .extend({ number: z.number().int().positive() });

export const gitOperationDefinitions = [
  defineOperation(
    "git.repos.discover",
    projectIdParamsSchema,
    gitDiscoveryResponseSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.git.repos.discover",
  ),
  defineOperation(
    "git.overview.get",
    gitRepoParamsSchema,
    gitOverviewResponseSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.git.overview.get",
  ),
  defineOperation(
    "git.project.files.status.get",
    projectIdParamsSchema,
    gitProjectFileStatusResponseSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.git.project.files.status.get",
  ),
  defineOperation(
    "git.branches.list",
    gitRepoParamsSchema,
    gitBranchListResponseSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.git.branches.list",
  ),
  defineOperation(
    "git.branch.create",
    gitCreateBranchParamsSchema,
    gitMutationResponseSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.git.branch.create",
  ),
  defineOperation(
    "git.branch.switch",
    gitSwitchBranchParamsSchema,
    gitMutationResponseSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.git.branch.switch",
  ),
  defineOperation(
    "git.file.diff.get",
    gitFileDiffParamsSchema,
    gitFileDiffResponseSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.git.file.diff.get",
  ),
  defineOperation(
    "git.file.stage",
    gitFileActionParamsSchema,
    gitMutationResponseSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.git.file.stage",
  ),
  defineOperation(
    "git.file.unstage",
    gitFileActionParamsSchema,
    gitMutationResponseSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.git.file.unstage",
  ),
  defineOperation(
    "git.file.discard",
    gitFileActionParamsSchema,
    gitMutationResponseSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.git.file.discard",
  ),
  defineOperation(
    "git.sync",
    gitRemoteOpParamsSchema,
    gitMutationResponseSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.git.sync",
  ),
  defineOperation(
    "git.push",
    gitRemoteOpParamsSchema,
    gitMutationResponseSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.git.push",
  ),
  defineOperation(
    "git.pull",
    gitRemoteOpParamsSchema,
    gitMutationResponseSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.git.pull",
  ),
  defineOperation(
    "git.fetch",
    gitRemoteOpParamsSchema,
    gitMutationResponseSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.git.fetch",
  ),
  defineOperation(
    "git.switchBaseAndPull",
    gitRemoteOpParamsSchema,
    gitMutationResponseSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.git.switchBaseAndPull",
  ),
  defineOperation(
    "github.status.get",
    gitRepoParamsSchema,
    githubStatusResponseSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.github.status.get",
  ),
  defineOperation(
    "github.pr.list",
    githubPrListParamsSchema,
    githubPrListResponseSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.github.pr.list",
  ),
  defineOperation(
    "github.pr.initial.get",
    githubPrParamsSchema,
    githubPrInitialSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.github.pr.initial.get",
  ),
  defineOperation(
    "github.pr.core.get",
    githubPrParamsSchema,
    githubPrCoreSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.github.pr.core.get",
  ),
  defineOperation(
    "github.pr.conversation.get",
    githubPrParamsSchema,
    githubPrConversationSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.github.pr.conversation.get",
  ),
  defineOperation(
    "github.pr.overview.get",
    githubPrParamsSchema,
    githubPrOverviewSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.github.pr.overview.get",
  ),
  defineOperation(
    "github.pr.commits.get",
    githubPrParamsSchema,
    githubPrCommitsResponseSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.github.pr.commits.get",
  ),
  defineOperation(
    "github.pr.checks.get",
    githubPrParamsSchema,
    githubPrChecksResponseSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.github.pr.checks.get",
  ),
  defineOperation(
    "github.pr.files.get",
    githubPrParamsSchema,
    githubPrFilesResponseSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.github.pr.files.get",
  ),
  defineOperation(
    "github.pr.file.diff.get",
    githubPrFileDiffParamsSchema,
    githubPrFileDiffResponseSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.github.pr.file.diff.get",
  ),
  defineOperation(
    "github.pr.checkout",
    githubPrParamsSchema,
    githubPrCheckoutResponseSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.github.pr.checkout",
  ),
  defineOperation(
    "github.pr.merge",
    githubPrMergeParamsSchema,
    githubPrMergeResponseSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.github.pr.merge",
  ),
] as const;
