export const EXPLORE_MAX_TASKS_PER_CALL = 8;
export const EXPLORE_MAX_ACTIVE_CHILDREN_PER_RUN = 8;
export const EXPLORE_MAX_ACTIVE_CHILDREN_GLOBAL = 8;
export const EXPLORE_MAX_CHILDREN_PER_RUN = 24;
